version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: kondate-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    #- ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3326:3306
  back:
    image: node:12
    tty: true
    volumes:
    - ./back:/app
    working_dir: /app
    depends_on: 
    - db
    ports:
    - '3500:3000'
  front:
    image: node:12
    tty: true
    volumes:
    - ./front:/app
    working_dir: /app
    ports:
    - "3003:8080"